[tool.poetry]
name = "isodesign"
version = "0.1.0"
description = ""
authors = ["llegregam <legregam@insa-toulouse.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.4"
numpy = "^1.26.4"
influx-si = "^7.0.2"
streamlit = "^1.33.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
