import logging
import shutil
from pathlib import Path
import pandas as pd 
from collections import namedtuple

logger = logging.getLogger(f"IsoDesign.{__name__}")  

# Namedtuples are placed outside the class to avoid pickling issues when saving the object
# namedtuple containing file path and data 
mtf_files_infos = namedtuple("mtf_files_infos", ['path', 'data']) 

class IoHandler:
    """
    Handles input and output operations.
 
    """
    FILES_EXTENSION = [".netw", ".tvar", ".mflux", ".miso", ".cnstr", ".mmet", ".opt"]
    
    def __init__(self):
        # Network file path
        self.netw_file_path = None
        # Metabolic model directory path 
        self.model_dir_path = None
        # Metabolic network model name
        self.model_name = None
        
        self.results_dir_path=None
        self.tmp_folder_path = None

    @staticmethod     
    def get_netw_file_path(input_path):
        """
        Get the directory path of the netw file (essential file containing 
        all reactions and transition labels). 

        :param input_path: str containing the path to the netw file 

        :return: Path object containing the path to the netw file
        """
        
        if not isinstance(input_path, str):
            msg = (f'"{input_path}" should be of type string and not {type(input_path)}.')
            logger.error(msg)
            raise TypeError(msg)

        netw_path = Path(input_path)

        if not netw_path.exists():
            msg = f"{netw_path} doesn't exist."
            logger.error(msg)
            raise ValueError(msg)
        
        if netw_path.suffix != ".netw":
            msg = f'{netw_path} is invalid. Please provide a file with ".netw" extension.'
            logger.error(msg)
            raise ValueError(msg)
        
        return netw_path
    
    # @staticmethod
    def load_metabolic_netw_model(self, model_name, model_dir_path):
        """ 
        Load the files representing the metabolic network model
        (MTF format files).

        :param model_name: str containing the name of the metabolic network model
        :param model_dir_path: str containing the path to the metabolic network model directory

        :return: dict containing the imported files as namedtuples (file path and data)
        """
        # Reset the dictionary to store imported files
        mtf_files = {}

        for file in model_dir_path.iterdir():
            if file.stem == model_name and file.suffix in self.FILES_EXTENSION:
                # Read the file and store its content in a namedtuple
                data = pd.read_csv(str(file),
                                    sep="\t",
                                    comment="#",
                                    header=None if file.suffix == ".netw" else 'infer',
                                    encoding="utf-8",
                                    on_bad_lines='skip')
                
                mtf_files.update({file.suffix[1:]: mtf_files_infos(file, data)})

        logger.debug(f"Imported files = {mtf_files}\n")
        return mtf_files
    
    def generate_tmp_folder(self, mtf_files):
        """
        Create a temporary folder to store all files generated by IsoDesign during its use.
        Copy the imported mtf files to the IsoDesign temp folder.All files that will be sent 
        to influx_si must be located in the same folder.

        :param mtf_files: dict containing the imported files as namedtuples (file path and data)
        """
        self.tmp_folder_path = Path(
            f"{self.results_dir_path}/{self.model_name}_tmp") 
        
        self.tmp_folder_path.mkdir(parents=True, exist_ok=True)

        logger.debug(f"Copy of the imported files to '{self.tmp_folder_path}'.\n")
        
        for file in mtf_files.values():
            # File paths are contained as first elements in the namedtuple
            # logger.debug(f"File path: {file.path}")
            shutil.copy(file.path, self.tmp_folder_path)

    def export_data(self, number, figure):
        """
        Export the results of the analysis to tsv files and an image file (html format).

        :param number: number corresponding to the analysis
        :param figure: plotly figure object
        """
        res_folder_path = Path(f"{self.results_dir_path}/{self.all_scores[number]['name']}_res")
        res_folder_path.mkdir(parents=True, exist_ok=True)

        # Export the dataframe and the scores table to tsv files
        self.all_scores[number]["dataframe"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_dataframe.tsv", index=False, sep="\t")
        self.all_scores[number]["columns_scores"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_scores.tsv", index=True, sep="\t")

        figure.write_html(f"{res_folder_path}/{self.all_scores[number]['name']}_barplot.html")
