import os
import logging
import shutil
from pathlib import Path
import pandas as pd 
from collections import namedtuple

logger = logging.getLogger(f"IsoDesign.{__name__}")  

# Namedtuples are placed outside the class to avoid pickling issues when saving the object
# namedtuple containing file path and data 
mtf_files_infos = namedtuple("mtf_files_infos", ['path', 'data']) 

class IoHandler:
    """
    Handles input and output operations.
 
    """
    FILES_EXTENSION = [".netw", ".tvar", ".mflux", ".miso", ".cnstr", ".mmet", ".opt"]
    
    def __init__(self):
        # Network file path
        self.netw_file_path = None
        # Metabolic model directory path 
        self.model_dir_path = None
        # Metabolic network model name
        self.model_name = None
        
        self.results_dir_path=None
        self.tmp_folder_path = None

    @staticmethod     
    def get_netw_file_path(input_path):
        """
        Get the directory path of the netw file (essential file containing 
        all reactions and transition labels). 

        :param input_path: str containing the path to the netw file 

        :return: Path object containing the path to the netw file
        """
        
        if not isinstance(input_path, str):
            msg = (f'"{input_path}" should be of type string and not {type(input_path)}.')
            logger.error(msg)
            raise TypeError(msg)

        netw_path = Path(input_path)

        if not netw_path.exists():
            msg = f"{netw_path} doesn't exist."
            logger.error(msg)
            raise ValueError(msg)
        
        if netw_path.suffix != ".netw":
            msg = f'{netw_path} is invalid. Please provide a file with ".netw" extension.'
            logger.error(msg)
            raise ValueError(msg)
        
        return netw_path
    
    # @staticmethod
    def load_metabolic_netw_model(self, model_name, model_dir_path):
        """ 
        Load the files representing the metabolic network model
        (MTF format files).

        :param model_name: str containing the name of the metabolic network model
        :param model_dir_path: str containing the path to the metabolic network model directory

        :return: dict containing the imported files as namedtuples (file path and data)
        """
        # Reset the dictionary to store imported files
        mtf_files = {}

        for file in model_dir_path.iterdir():
            if file.stem == model_name and file.suffix in self.FILES_EXTENSION:
                # Read the file and store its content in a namedtuple
                data = pd.read_csv(str(file),
                                    sep="\t",
                                    comment="#",
                                    header=None if file.suffix == ".netw" else 'infer',
                                    encoding="utf-8",
                                    on_bad_lines='skip')
                
                mtf_files.update({file.suffix[1:]: mtf_files_infos(file, data)})

        logger.debug(f"Imported files = {mtf_files}\n")
        return mtf_files
    
    def generate_tmp_folder(self, mtf_files):
        """
        Create a temporary folder to store all files generated by IsoDesign during its use.
        Copy the imported mtf files to the IsoDesign temp folder.All files that will be sent 
        to influx_si must be located in the same folder.

        :param mtf_files: dict containing the imported files as namedtuples (file path and data)
        """
        self.tmp_folder_path = Path(
            f"{self.results_dir_path}/{self.model_name}_tmp") 
        
        self.tmp_folder_path.mkdir(parents=True, exist_ok=True)

        logger.debug(f"Copy of the imported files to '{self.tmp_folder_path}'.\n")
        
        for file in mtf_files.values():
            # File paths are contained as first elements in the namedtuple
            # logger.debug(f"File path: {file.path}")
            shutil.copy(file.path, self.tmp_folder_path)
    
    def generate_linp_files(self, label_inputs, linp_dfs):
        """
        Generates linp files (TSV format) in the temp folder (self.tmp_folder_path). 
        Each file contains a combination of labelled substrates. 
        
        A file is generated containing a mapping that associates each file 
        number with its respective combinations. 

        :param label_inputs: LabelInput object containing the isotopomer group and the generated combinations
        :param linp_dfs: dict containing the linp configuration dataframes for each combination of labelled substrates. 
                        Dataframes are stored in dictionary format.
       
        """
        self._clear_previous_linp()

        # create mapping to associate file number with its respective combinations
        with open(os.path.join(str(self.results_dir_path), f'{self.model_name}_IDs_combinations.tsv'), 'w', encoding="utf-8") as f:
            # Write file column names
            f.write("ID\t" + 
                    "\t".join([f"{specie}_{isotopomer}" for specie, isotopomer in zip(label_inputs.names, label_inputs.labelling_patterns)]) + 
                    "\tPrice\n")
            for index, dataframes in linp_dfs.items():
                # Dataframes are stored in dictionary format
                df = pd.DataFrame.from_dict(dataframes)
                # Write the content of the linp files in the tsv file
                f.write(f"{index}\t" + 
                        "\t".join(map(str, df["Value"])) +
                        f"\t{df['Price'].sum()}\n")
                # Remove rows with value = 0 (no values equal to 0 in ".linp" files)
                df = df.loc[df["Value"] != 0]
                df.to_csv(os.path.join(str(self.tmp_folder_path), f"{index}.linp"), sep="\t", index=False)

        logger.info(f"{len(linp_dfs.keys())} linp files have been generated in {self.tmp_folder_path}.")

    def _clear_previous_linp(self):
        """
        Clear the ".linp" files generated by the previous run.    
        """
        for linp_files in self.tmp_folder_path.iterdir():
            if linp_files.is_file() and linp_files.name.endswith(".linp"):
                os.remove(linp_files)
    
    def generate_vmtf_file(self, vmtf_dict):
        """
        Generate the vmtf file (TSV format) in the temp folder (self.tmp_folder_path).

        :param vmtf_dict: dict containing the vmtf configuration dataframes for each combination 
                        of labelled substrates.
        """   
        df = pd.DataFrame.from_dict(vmtf_dict)
  
        logger.debug(f"Creation of the vmtf file containing these files :\n {df}")
        df.to_csv(f"{self.tmp_folder_path}/{self.model_name}.vmtf", sep="\t", index=False)

        # logger.info(f"Vmtf file has been generated in '{self.tmp_folder_path}.'\n")

    def export_data(self, number, figure):
        """
        Export the results of the analysis to tsv files and an image file (html format).

        :param number: number corresponding to the analysis
        :param figure: plotly figure object
        """
        res_folder_path = Path(f"{self.results_dir_path}/{self.all_scores[number]['name']}_res")
        res_folder_path.mkdir(parents=True, exist_ok=True)

        # Export the dataframe and the scores table to tsv files
        self.all_scores[number]["dataframe"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_dataframe.tsv", index=False, sep="\t")
        self.all_scores[number]["columns_scores"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_scores.tsv", index=True, sep="\t")

        figure.write_html(f"{res_folder_path}/{self.all_scores[number]['name']}_barplot.html")
