
import logging
import os
import shutil
import tempfile
import pickle
from collections import namedtuple
from pathlib import Path
import numpy as np
import subprocess
import isodesign
import time 

import pandas as pd
from influx_si import C13_ftbl, txt2ftbl

from isodesign.base.isotopomer import Isotopomer
from isodesign.base.label_input import LabelInput
from isodesign.base.score import ScoreHandler

logger = logging.getLogger(f"IsoDesign.{__name__}")  

# Namedtuples are placed outside the class to avoid pickling issues when saving the Process object
# namedtuple containing the number of labeled inputs and the total price for each linp file
linp_files_infos = namedtuple("linp_files_infos", ["nb_labeled_inputs", "total_price"])

class Process:
    """
    The Process class is the main class to organise IsoDesign functionalities.
    
    Key features:
    - load the files representing the metabolic network model (MTF format files)
    - generating combinations of isotopomers that are stored in influx_si .linp files
    - runs simulations with influx_si to get predicted fluxes and associated SDs
    - generates a summary.
    """

    def __init__(self, data : dict):
        """
        :param data: dictionary containing the imported files as namedtuples 
                    (file path and data) (e.g. {'netw': namedtuple(path, data), 
                    'tvar': mnamedtuple(path, data), ...})
        """
        self.data = data
        # # Version of the isodesign package
        # self.isodesign_version = isodesign.__version__

        # LabelInput object
        # To use the generate_labelling_combinations method
        self.label_input = None

        # Elements analyzed (substrates, metabolites, etc.) in the network using the model_analysis method
        self.netan = {}
        # summary dataframe generated after simulation with influx_si
        self.summary_dataframe = None
        # filtered dataframe after filter use
        self.filtered_dataframe = None
        # Dictionary containing isotopomers
        # key : substrate name, value : list of isotopomers
        self.isotopomers = {}
        # # Get the tvar.def file generated during the model analysis
        # self.tvar_def_file = None
        # Dictionary to store the number of labeled inputs and the total isotopomer prices of each linp file 
        # Key : linp file name, value : namedtuple containing the number of labeled inputs and the total price
        self.linp_files_infos = None
        # Dictionary containing the number of structurally identified fluxes (obtained from the ‘tvar.sim’ files) 
        # Key : file name, value : number of structurally identified fluxes
        self.structures_identified = {}
        # List storing linp file data in the form of dictionaries
        # each dictionary representing a combination of labelled substrates.
        self.linp_dataframes = None
        
        # Dictionary containing element to build the vmtf file
        self.vmtf_dict = None
      
        # List of command line arguments to pass to influx_si
        self.command_list = None
        # List of linp dataframes to remove
        self.linp_config_deleted = {}

        # Stores the scores generated after application of the scoring criteria 
        self.scores : pd.DataFrame = None
        # Stores all the scores generated by the user
        self.all_scores = {}   
        # All this attributes are used to store the results of the analysis 
        self.filters : dict = None
        self.selected_criteria : list = []
        self.criteria_parameters : dict = None
        self.applied_operations = None
   
    # @staticmethod
    def model_analysis(self, model_path, model_name):
        """
        Analyze model network to identify substrates, metabolites, etc by using 
        modules from influx_si.

        :param model_path: path to the metabolic network model directory
        :param model_name: name of the metabolic network model
        """
        # Reset self.netan to a new empty dictionary
        # Useful if you want to reuse the function for another prefix
        self.netan = {}
        # Use a temporary directory to store files generated by the modules
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)

            # Copy all files from model_directory_path to the temporary directory
            files_to_copy = [f for f in model_path.iterdir() if f.is_file()]
            for file in files_to_copy:
                shutil.copy(file, tmpdir_path)

            # will contain the paths to the ftbl files generated by the txt2ftbl module
            li_ftbl = []  
            # convert mtfs to ftbl
            txt2ftbl.main(["--prefix", os.path.join(str(tmpdir), model_name)], li_ftbl)

            # # get the tvar.def file
            # for file in os.listdir(tmpdir):
            #     if file.endswith(".tvar.def"):
            #         self.tvar_def_file = pd.read_csv(os.path.join(tmpdir, file), sep="\t", comment="/")

            # parse and analyze ftbl stored in li_ftbl
            model: dict = C13_ftbl.ftbl_parse(li_ftbl[0])

            emu = False # can be advantageous to set to "True" when there are
            # only mass measurements
            fullsys = False
            case_i = False # for influx_i, must be "True"
            # analyze the model dictionary to find different network elements
            # such as substrates, metabolites...
            C13_ftbl.ftbl_netan(model, self.netan, emu, fullsys, case_i)
        logger.debug(f"self.netan dictionary keys : {self.netan.keys()}\n")
        logger.info("Network analysis finished successfully.\n")

    @staticmethod
    def save_process_to_file(obj, results_dir_path, model_name):
        """
        Save the process to a pickle file in the model directory.

        :param obj: object to save
        :param results_dir_path: path to the results directory
        :param model_name: name of the metabolic network model
        """
         
        output_file_tmp = Path(results_dir_path, model_name + "_tmp.pkl")
        output_file = Path(results_dir_path, model_name + ".pkl")

        try:
            with open(output_file_tmp, 'wb') as file:
                pickle.dump(obj, file)
            output_file.unlink(missing_ok=True)
            output_file_tmp.rename(output_file)
        except Exception as e:
            raise ValueError(f"An unknown error has occured when saving the process file: {e}")
    
    def configure_unlabelled_form(self):
        """
        Add the unlabelled form of the inputs to the isotopomers dictionary 
        (key: substrate name, value: list of isotopomers) with default values.

        """
        for substrates_name in self.netan["input"]:
            self.isotopomers[substrates_name] = [Isotopomer(substrates_name, 
                                                       self.netan["Clen"][substrates_name] * "0", 
                                                       intervals_nb=10, 
                                                       lower_bound=1, 
                                                       upper_bound=1, 
                                                       price=None)]

    
    def add_isotopomer(self, substrate_name:str, labelling:str, intervals_nb:int, lower_b:int, upper_b:int, price:float=None):	
        """
        Add isotopomer to the isotopomers dictionary (self.isotopomers). 

        :param substrate_name: name of the substrate
        :param labelling: labelling of the isotopomer
        :param intervals_nb: number of intervals to test
        :param lower_b: lower bound
        :param upper_b: upper bound
        :param price: price of the isotopomer. 
        """
        
        isotopomer = Isotopomer(substrate_name, labelling, intervals_nb, lower_b, upper_b, price)
        
        # Check if the substrate is in the network inputs
        if substrate_name not in self.netan["input"]:
            raise ValueError(f"{substrate_name} not found in the network inputs. Please add isotopomers only for the input substrates.")
        # Check if the labelling length is equal to the number of carbons in the substrate
        # by using clen (carbon length) from the netan (network analysis) dictionary
        if len(labelling) != self.netan["Clen"][substrate_name]:
            raise ValueError(f"Number of atoms for {substrate_name} should be equal to {self.netan['Clen'][substrate_name]}")
        # Check if the labelling already exists for the substrate 
        # each substrate must have unique isotopomers 
        if labelling in [isotopomer.labelling for isotopomer in self.isotopomers[substrate_name]]:
            # logger.error(f"Isotopomer {labelling} already exists for {substrate_name}")
            raise ValueError(f"Isotopomer {labelling} already exists for {substrate_name}")
            
        self.isotopomers[substrate_name].append(isotopomer)
            
    

    def remove_isotopomer(self, substrate:str, labelling:str):
        """
        Remove isotopomer from the isotopomer dictionary (self.isotopomers) 
        according to the substrate name and labelling.

        :param substrate: substrate name
        :param labelling: labelling for isotopomer to remove

        """

        if substrate not in self.isotopomers:
            raise ValueError(f"{substrate} not found in the isotopomers dictionary.")

        if labelling not in [isotopomer.labelling for isotopomer in self.isotopomers[f"{substrate}"]]:
            raise ValueError(f"Isotopomer {labelling} not found for {substrate}.")
    
        for isotopomer in self.isotopomers[f"{substrate}"]:
            if isotopomer.labelling == labelling and isotopomer.name == substrate:
                self.isotopomers[f"{substrate}"].remove(isotopomer)

    def generate_combinations(self):
        """
        Generate all possible combinations of labelled substrates 
        using the LabelInput class.
        """
        # Check if "self.isotopomers" is not empty
        if not self.isotopomers:
            raise ValueError("No isotopomers have been added. Please add at least one isotopomer.")
        # Check if there is at least one isotopomer for each substrate
        for substrates, isotopomers in self.isotopomers.items():
            if not isotopomers:
                raise ValueError(f"No isotopomers for {substrates}. Please add at least one isotopomer.")
        
        # Initialize the LabelInput object with the isotopomers dictionary
        self.label_input = LabelInput(self.isotopomers)
        logger.info(f"Label Input - {self.label_input}")

        self.label_input.generate_labelling_combinations()
        
        logger.debug(
            f"Isotopomers combinations:"
            f"{self.label_input.isotopomer_combinations}\n"
        )

        
    def _get_isotopomer_price(self, isotopomer_labelling:str, isotopomer_name:str):
        """ 
        Get the price of an isotopomer based on its labelling and name 
        from the isotopomers dictionary.
        
        :param isotopomer_labelling: isotopomer labelling
        :param isotopomer_name: isotopomer name
        """

        for isotopomers_list in self.isotopomers.values():
            for isotopomer in isotopomers_list:
                if isotopomer.labelling == isotopomer_labelling and isotopomer.name == isotopomer_name:
                    return isotopomer.price
    
    def configure_linp_files(self):
        """
        This method configures the structure and content of future 
        linp files, a TSV format used for labelled simulations, 
        grouping label input forms and their fractions. 
        Dataframes are generated in linp format, each containing
        a specific combination of labelled substrates. These dataframes 
        are then stored and used to create the final linp files.

        """
        self.linp_dataframes = {}

        # Calculate the number of digits based on the total number of files
        total_files = len(self.label_input.isotopomer_combinations["All_combinations"])
        num_digits = len(str(total_files))
        
        # Generate a dataframe for each pair of isotopomers 
        for index, pair in enumerate(self.label_input.isotopomer_combinations["All_combinations"], start=1):
            df = pd.DataFrame({'Id': None,
                                'Comment': None,
                                'Specie': self.label_input.names,
                                'Isotopomer': self.label_input.labelling_patterns,
                                'Value': pair.astype(float)})

            # add a column "Price" containing the price of each isotopomer multiplied by its fraction
            # applies the 'get_isotopomer_price' method to each row (axis=1) in the dataframe 'df'
            df["Price"] = df.apply(lambda x: self._get_isotopomer_price(x["Isotopomer"], x["Specie"]), axis=1) * df["Value"]
            # logger.debug(f"Folder path : {self.tmp_folder_path}\n Dataframe {index:02d}:\n {df}")
            
            # Store the dataframe in the linp_dataframes dictionary
            # key : ID_{index}, value : dataframe in dictionary format
            self.linp_dataframes.update({f"ID_{index:0{num_digits}d}": df.to_dict(orient="list")})            
            

    def remove_linp_configuration(self, index_to_remove:list):
        """
        Removes linp DataFrames from the linp_dataframes 
        list according to the indices specified in the 
        list provided. 

        :param index_to_remove: list of indices to remove 
                                from linp_dataframes
        """   
        to_remove = []

        for index in index_to_remove:
            if index >= len(self.linp_dataframes):
                raise IndexError(f"Index {index} is out of range. Please provide valid indices between 0 and {len(self.linp_dataframes)-1}.")
        
        for index, (key, value) in enumerate(self.linp_dataframes.items()):
            if index in index_to_remove:
                # Store the linp DataFrames to remove in the linp_to_remove dictionary
                # key : index, value : dictionary containing the id of the linp DataFrame as key and its content as value
                # example : {0: {'ID_01': {'Id': None, 'Comment': None, 'Specie': ['Gluc', 'Gluc'], 'Isotopomer': ['111111', '100000'], 'Value': [0.5, 0.5], 'Price': [10.0, 10.0]}}
                self.linp_config_deleted[index] = {key: value}
                to_remove.append(key)
            
        for id in to_remove:
            logger.info(f"Combination(s) removed : {id}\n") 
            logger.debug(f"{id} : {self.linp_dataframes[id]}\n")
            del self.linp_dataframes[id]  
             
    
    def reintegrate_linp_configuration(self, index_to_reintegrate:list):
        """
        Reintegrates linp DataFrames into the linp_dataframes 
        list according to the indices specified in the 
        list provided. 

        :param index_to_reintegrate: list of indices to reintegrate 
                                    into linp_dataframes.
        """
        # Get the keys of the linp DataFrames to reintegrate
        for index in index_to_reintegrate:
            for id, value in self.linp_config_deleted[index].items():
                all_linp_configurations = list(self.linp_dataframes.items())
                all_linp_configurations.insert(index, (id, value))
                self.linp_dataframes = dict(sorted(all_linp_configurations))
                logger.info(f"Combination reintegrated : {id}\n")
                logger.debug(f"{id} : {value}\n")
            del self.linp_config_deleted[index]
    
    def get_linp_infos(self):
        """
        Store the number of labeled inputs and the total price of each linp file in the linp_files_infos dictionary.
        It will be used in the rating criteria.

        """
        self.linp_files_infos = {}

        for index, dictionary in self.linp_dataframes.items():
            self.linp_files_infos[f"{index}"] = linp_files_infos(len([isotopomer for isotopomer in dictionary["Isotopomer"] if "1" in isotopomer]),
                                                                 dictionary["Price"])
    
    def configure_vmtf_files(self):
        """
        Configure the vmtf file (TSV format) that permit to combine variable
        and constant parts of a network model.
        This file contained columns using imported files extensions. Each row contains
        imported files names that will be used to produce a ftbl file used in the calculation. 
        Each row have ftbl column with unique and non empty name.
        """
        if self.linp_dataframes:
            self.vmtf_dict = {"Id": None,
                            "Comment": None,
                            "linp": [f"{index}" for index in self.linp_dataframes.keys()],
                            "ftbl": [f"{index}" for index in self.linp_dataframes.keys()]}
        
    def influx_simulation(self, param_list: list, tmp_folder: Path):
        """
        Run the simulation using the specified influx_si mode (stationary or instationary).

        :param param_list: List of command-line arguments to pass to influx_si.
        :param tmp_folder: Path to the temporary folder where the files required for the 
                            simulation are located.

        :return: subprocess.Popen object representing the running simulation process.
        """
        # Change directory to the folder containing all the file to use for influx_si
        os.chdir(tmp_folder)

        self.command_list = param_list
        logger.info(f"Command to run: {self.command_list}")

        # result = subprocess.Popen(self.command_list, stderr=subprocess.PIPE, text=True)
        
        # stdout, stderr = result.communicate()
        # if result.returncode != 0:
        #     self._check_err_files()
        #     logger.error(f"Error during simulation: {result.stderr}")
        #     raise RuntimeError(f"Error during simulation: {result.stderr}")
        
        # self._get_influx_sim_res_files()

        # logger.info("Simulation finished successfully.\n")
        result = subprocess.Popen(self.command_list, stderr=subprocess.PIPE, text=True)
        
        return result
        # while True:
        #     if result.poll() is not None:
        #         self._get_influx_sim_res_files(tmp_folder)
        #         return
        #     if result.returncode is not None and result.returncode != 0:
        #         self._check_err_files(tmp_folder)
        #         logger.error(f"Error during simulation: {result.stderr}")
        #         raise RuntimeError(f"Error during simulation: {result.stderr}")
        #     time.sleep(0.2)
        
    def _get_tvar_sim_files(self, tmp_folder: Path):
        """
        Get the paths to the tvar.sim files generated by influx_si
        after the simulation.

        :param tmp_folder: Path to the temporary folder where the 
                            simulation files are located.

        :return: list of paths to the tvar.sim files
        """
        # use os.walk to generate the names of folders, subfolders and files in a given directory
        tvar_sim_paths = [
            Path(f"{root}/{files}")
            for (root, _, files_names) in os.walk(tmp_folder)
            for files in files_names
            if files.endswith(".tvar.sim")
        ]

        if not tvar_sim_paths:
            raise ValueError(
                "No tvar.sim files found. Please check if the simulation with influx_si was successful."
            )
        
        logger.debug(f"List of tvar.sim file paths : \n {tvar_sim_paths}")
        return tvar_sim_paths
        # Get the number of structurally identified fluxes from each tvar.sim file
        # self.obtain_structures_identified()

    def configurate_summary(self, tmp_folder:Path):
        """
        Read the tvar.sim files and configure a summary dataframe containing :
            - flux names, flux types,
            - the flux values in the tvar.sim files,
            - the difference between the flux values in the input tvar file and the tvar.sim files,
            - flux SDs in each tvar.sim file

        :param tmp_folder: Path to the temporary folder where the 
                            simulation files are located.
        """
        
        tvar_sim_paths = self._get_tvar_sim_files(tmp_folder)

        if tvar_sim_paths :
            # dictionary containing columns "Name", "Kind" and "SD" from each tvar.sim file
            tvar_sim_dataframes = {
                f'{file_path.name.split(".")[0]}': pd.read_csv(
                    file_path, sep="\t", usecols=["Name", "Kind", "SD"], index_col=["Name", "Kind"]).rename(
                        columns={"SD": f"{file_path.name.split('.')[0]}"})
                for file_path in tvar_sim_paths
            }
            tvar_sim_dataframes = pd.concat(tvar_sim_dataframes.values(), axis=1, join="inner")
            logger.debug(f"tvar_sim_dataframes: {tvar_sim_dataframes}")

            # take the flux values from the first tvar.sim file 
            # flux values are the same in all tvar.sim files
            tvar_sim_values = pd.read_csv(tvar_sim_paths[0], sep="\t", usecols=["Value", "Name", "Kind"]) 

            # take the "Name", "Kind" and "Value" columns from the input tvar file
            input_tvar_file = self.data['tvar'].data[["Name", "Kind", "Value"]]
            # merge data from the input tvar file with data from tvar.sim files based on flux names and kind
            merged_tvar = pd.merge(input_tvar_file, tvar_sim_values, on=["Name", "Kind"], how="outer", suffixes=('_init', None))
            merged_tvar["Value difference"] = merged_tvar["Value_init"] - merged_tvar["Value"]
            logger.debug(f"Merged_tvar_values : {merged_tvar}")

            # merge the "merged_tvar" dataframe with concatenated dataframes from the "tvar_sim_dataframes" dataframes
            # delete the "Value_tvar_init" column, which is not required
            self.summary_dataframe = pd.merge(
                merged_tvar, tvar_sim_dataframes, on=["Name", "Kind"]).rename(columns={"Value_init": " Intial flux value"})
            # logger.debug(f"Summary dataframe present in '{self.results_dir_path}' : {self.summary_dataframe}\n")
    
    def obtain_structures_identified(self):
        """
        Obtain the number of structurally identified fluxes from each "tvar.sim" files
        """
        # get the number of structurally identified fluxes from each "tvar.sim" files
        # Fluxes are considered structurally identified if they have an SD <= 10000
        self.structures_identified = {file_path.name.split(".")[0]: sum(
                [len(struct)for struct in pd.read_csv(file_path, sep="\t", usecols=["Struct_identif"]).values if struct == "yes"]) 
                for file_path in self.tvar_sim_paths}

    def filter_data(self, fluxes_names:list=None, kind:list=None, pathways:list=None):
        """
        Filters summary dataframe by fluxes names, kind and/or metabolic pathway 

        :param fluxes_names: list of fluxes names to be displayed 
        :param kind: "NET", "XCH", "METAB"
        :param pathway: name of metabolic pathways to be displayed  

        :return: filtered dataframe
        """
        
        self.filtered_dataframe = self.summary_dataframe.copy()

        if fluxes_names:
            # keep only rows with fluxes names in the list
            self.filtered_dataframe = self.filtered_dataframe.loc[self.filtered_dataframe["Name"].isin(fluxes_names)]
        if kind:
            # keep only rows with kind in the list
            self.filtered_dataframe = self.filtered_dataframe.loc[self.filtered_dataframe["Kind"].isin(kind)]
        if pathways:
            # list storing all fluxes concerned by the selected metabolic pathway(s) 
            all_fluxes = []
            for pathway_name in pathways:
                # key "pathway" in netan dictionary contains another dictionary as value
                # In netan dictionary, key : pathway names, value : list with fluxes names involved in this pathway as value
                all_fluxes.extend(self.netan["pathway"][pathway_name])
        
            self.filtered_dataframe = self.filtered_dataframe.loc[self.filtered_dataframe["Name"].isin(all_fluxes)]
        # Store the filters used in the analysis
        self.filters = {
            "fluxes_names": fluxes_names,
            "kind": kind,
            "pathways": pathways}
        # logger.info(f"Filtered dataframe :\n{self.filtered_dataframe}")

        # return self.filtered_dataframe

    def generate_score(self, method :list, operation = None, **kwargs):
        """
        Generate a score for each labelled substrate combination according 
        on the criteria method(s) applied.

        :param method: list of criteria methods to apply
        :param operation: operation to apply to the scores (Addition, Multiply, Divide)
        :param kwargs: additional arguments for the rating methods
        """
        score_object = ScoreHandler(self.filtered_dataframe.iloc[:, 5:] if self.filtered_dataframe is not None else self.summary_dataframe.iloc[:, 5:])
        
        score_object.apply_criteria(method, **kwargs)
        if operation:
            score_object.apply_operations(operation)

        # Store the scores in a dataframe    
        self.scores = pd.DataFrame.from_dict(score_object.columns_scores, 
                                   orient='index')
        # Store the criteria, parameters and operations used to generate the scores
        self.selected_criteria = method
        self.criteria_parameters = kwargs
        self.applied_operations = operation

        # logger.debug(f"Scores applied to the dataframe :\n{score_object.columns_scores}")
    
    def apply_log(self):
        """
        Apply a log of 10 to the values contained in 
        the score table (stored in the self.scores attribute).
        """
        self.scores=np.log10(self.scores)

    def register_scores(self, number, block_name):
        """
        Stores the analysis data (dataframe, criteria, criteria parameters,
        score table, filters and operations) in a dictionary.
        This method updates the all_scores dictionary with a new key
        identified by the specified "number".

        :param number: number corresponding to the analysis 
        """
        self.all_scores.update(
            {number: {
                "name" : block_name,
                "dataframe": self.filtered_dataframe,
                "filters": self.filters,
                "criteria": self.selected_criteria,
                "criteria_parameters": self.criteria_parameters,
                "columns_scores": self.scores, 
                "applied_operations": self.applied_operations,
            }}
        )  

        logger.debug(self.all_scores)             

    # def export_data(self, number, figure):
    #     """
    #     Export the results of the analysis to tsv files and an image file (html format).

    #     :param number: number corresponding to the analysis
    #     :param figure: plotly figure object
    #     """
    #     res_folder_path = Path(f"{self.results_dir_path}/{self.all_scores[number]['name']}_res")
    #     res_folder_path.mkdir(parents=True, exist_ok=True)

    #     # Export the dataframe and the scores table to tsv files
    #     self.all_scores[number]["dataframe"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_dataframe.tsv", index=False, sep="\t")
    #     self.all_scores[number]["columns_scores"].to_csv(f"{res_folder_path}/{self.all_scores[number]['name']}_scores.tsv", index=True, sep="\t")

    #     figure.write_html(f"{res_folder_path}/{self.all_scores[number]['name']}_barplot.html")


# if __name__ == "__main__":

#     test = Process()
#     test.get_netw_file_path(r"C:\Users\kouakou\Documents\data_CBE\020_ok\microfluxpCC25.netw")
#     test.results_dir_path = r"C:\Users\kouakou\Documents\data_CBE\020_ok"
#     test.load_metabolic_netw_model()
#     test.model_analysis()
#     test.create_tmp_folder()

#     test.configure_unlabelled_form()
#     test.add_isotopomer("Gluc_out", "100000", 2, 0, 1)
#     test.add_isotopomer("Arg_out", "100000", 2, 0, 1)
#     # test.add_isotopomer("Met_out", "10000", 2, 0, 1)
#     # test.add_isotopomer("Thr_out", "1000", 2, 0, 1)
#     test.generate_combinations()

#     test.configure_linp_files()
    
#     test.generate_linp_files()
#     test.generate_vmtf_file()

#     command_list = ["influx_s","--prefix", test.metabolic_netw_model_name, "--emu", "--ln", "--noopt"]
#     test.influx_simulation(command_list)
#     print(test.tvar_sim_paths)
#     test.generate_summary()
#     print(test.summary_dataframe)
# #     # test.save_process_to_file()
#     test.filter_data(kind=["NET"])
#     test.generate_score(["sum of SDs", "number of fluxes with SDs < threshold"], threshold=1)
# #     # test.draw_barplot(test.scores)
# #     # test.register_scores(1)

#     # test.export_data("score_1")

    

